avatar-badge done
kushalsourav/enma pull request #1
Opened 2022-02-10 17:02 UTC by kushalsourav

avatar and badges completed

2022-02-10 17:49 UTC, ashishkatiyar2404 requested changes

2022-02-10 17:49 UTC, ashishkatiyar2404 commented on packages/components/badge.css
> +    background-color: green;
use variables for colors.
I have seen you  already use but also use here.

2022-02-10 17:51 UTC, ashishkatiyar2404 commented
All looks good to me.
but Speed up, deadline is near.

2022-02-10 19:43 UTC, dipen2000 approved these changes
Looks good man , you are consistent with the naming and you are using variables for colors and all those things. 
![image](https://user-images.githubusercontent.com/57138163/153484402-cef2520f-278e-4bb1-b594-eb3c1ac1022c.png)

There is some problem here with the alignment do check that and other than that you are good to go.

2022-02-10 19:45 UTC, dipen2000 commented
The deadline is very near and you have a lot of ground to cover so buckle up now and complete this thing.
best of luck.

2022-02-11 02:51 UTC, kushalsourav commented
> Looks good man , you are consistent with the naming and you are using variables for colors and all those things. ![image](https://user-images.githubusercontent.com/57138163/153484402-cef2520f-278e-4bb1-b594-eb3c1ac1022c.png)
> 
> There is some problem here with the alignment do check that and other than that you are good to go.

position absolute is adding padding automatically for it , when i remove positioning it layers properly but positioning is imp for using that component

2022-02-11 03:02 UTC, merged